import { PublisherCheckReport } from '../src/types.js';

export const FALLBACK_DEMO_REPORT: PublisherCheckReport = {
  id: 'rep_demo_thedailyfront',
  targetUrl: 'https://thedailyfront.com',
  normalizedDomain: 'thedailyfront.com',
  analyzedAt: new Date().toISOString(),
  isCached: false,
  isDemoData: true,
  overallRiskLevel: 'REVIEW RECOMMENDED',
  signalCounts: {
    verified: 5,
    signal: 1,
    notChecked: 0,
    total: 6,
  },
  checksCompletedCount: 6,
  checksTotalCount: 6,
  summaryVerdict: 'DEMO DATA — NOT A LIVE SCAN: Caution signal was detected in this demonstration dataset regarding contribution page availability.',
  
  publishing: {
    status: 'active',
    signalStatus: 'VERIFIED_POSITIVE',
    signalState: 'VERIFIED',
    headline: 'Publication dates identified on 10 of 10 sampled articles',
    latestPostDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    totalArticlesSampled: 10,
    sampledArticlesWithDates: 10,
    totalArticlesOnSite: null,
    totalArticlesOnSiteSource: null,
    explanation: 'PublisherCheck analyzed the latest 10 accessible article pages from this website. Publication dates were identified for 10 of 10 sampled articles.',
    evidence: [
      {
        id: 'demo-pub-1',
        type: 'url',
        title: 'How Remote Teams Scale Engineering Velocity',
        url: 'https://thedailyfront.com/tech/scaling-remote-engineering',
        detail: 'Published 4 days ago',
      },
      {
        id: 'demo-pub-2',
        type: 'url',
        title: 'Top Boutique Hotels in Southern Europe for 2026',
        url: 'https://thedailyfront.com/travel/top-boutique-hotels-europe',
        detail: 'Published 11 days ago',
      },
      {
        id: 'demo-pub-3',
        type: 'url',
        title: 'Navigating Sustainable Investing & Clean Tech Funds',
        url: 'https://thedailyfront.com/finance/sustainable-investing-guide',
        detail: 'Published 18 days ago',
      },
    ],
  },

  outboundLinks: {
    status: 'moderate',
    signalStatus: 'SIGNAL_NEUTRAL',
    signalState: 'VERIFIED',
    headline: 'Moderate outbound links (3.8 external links per sampled page)',
    totalArticlesSampled: 15,
    totalArticlePagesSampled: 15,
    totalExternalLinks: 57,
    totalInternalLinks: 124,
    avgExternalPerArticle: 3.8,
    maxExternalOnSingleArticle: 8,
    followedLinksCount: 42,
    nofollowLinksCount: 11,
    sponsoredLinksCount: 4,
    ugcLinksCount: 0,
    unknownRelLinksCount: 0,
    relAudit: {
      follow: 42,
      nofollow: 11,
      sponsored: 4,
      ugc: 0,
      unknown: 0,
      rawRelTokenCounts: {
        nofollowTokenCount: 11,
        sponsoredTokenCount: 4,
        ugcTokenCount: 0,
        followTokenCount: 0,
        unknownTokensFound: [],
      },
    },
    topExternalDomains: [
      { domain: 'github.com', count: 9, isCommonPlatform: true, articlesCount: 5, category: 'platform' },
      { domain: 'nytimes.com', count: 6, isCommonPlatform: true, articlesCount: 4, category: 'editorial_ref' },
      { domain: 'cloudmetrics-analytics.io', count: 5, isCommonPlatform: false, articlesCount: 3, category: 'commercial' },
      { domain: 'bloomberg.com', count: 4, isCommonPlatform: true, articlesCount: 3, category: 'editorial_ref' },
      { domain: 'hotelres-booking.net', count: 4, isCommonPlatform: false, articlesCount: 2, category: 'commercial' },
    ],
    linkClassification: {
      editorialCitationCount: 18,
      commercialOrAffiliateCount: 9,
      affiliateMonetizedCount: 4,
      commercialBrandCount: 5,
      socialOrCommunityCount: 8,
      platformOrTechCount: 12,
      generalExternalCount: 10,
      keywordAnchorCount: 28,
      brandOrDomainAnchorCount: 15,
      genericAnchorCount: 10,
      emptyOrImageAnchorCount: 4,
      classifiedDetails: {
        editorialDomains: ['nytimes.com', 'bloomberg.com'],
        commercialDomains: ['cloudmetrics-analytics.io', 'hotelres-booking.net'],
        affiliateTaggedCount: 4,
        commercialAnchorSamples: ['"check devops pricing" -> cloudmetrics-analytics.io'],
      },
    },
    pagesWithHighestExternalLinks: [
      {
        url: 'https://thedailyfront.com/tech/best-devops-monitoring-stacks',
        title: 'Best DevOps Monitoring Stacks for High-Throughput APIs',
        externalLinksCount: 8,
        internalLinksCount: 5,
        topExternalDomains: ['cloudmetrics-analytics.io', 'github.com'],
      },
      {
        url: 'https://thedailyfront.com/travel/top-boutique-hotels-europe',
        title: 'Top Boutique Hotels in Southern Europe for 2026',
        externalLinksCount: 7,
        internalLinksCount: 6,
        topExternalDomains: ['hotelres-booking.net'],
      },
    ],
    explanation: 'Average external link density is 3.8 per sampled page across 15 sampled pages.',
    evidence: [
      {
        id: 'demo-ext-1',
        type: 'stat',
        title: '3.8 external links per sampled page across 15 sampled pages',
        detail: '57 total external links (42 dofollow, 11 nofollow, 4 sponsored).',
      },
    ],
  },

  guestPostSignals: {
    status: 'found',
    signalStatus: 'SIGNAL_CAUTION',
    signalState: 'SIGNAL',
    headline: 'An explicit contribution page was detected',
    contributionPagesFound: [
      {
        title: 'Write For Us — Editorial Guidelines',
        url: 'https://thedailyfront.com/write-for-us',
        matchType: 'url_slug',
        matchedPhrase: 'write for us',
      },
    ],
    explanation: 'An explicit contribution or guest submission page was detected at public link: https://thedailyfront.com/write-for-us. This is an observable signal and not proof of paid links.',
    evidence: [
      {
        id: 'demo-gp-1',
        type: 'url',
        title: 'Submission Guidelines Page',
        detail: 'Matched phrase "write for us" at https://thedailyfront.com/write-for-us',
        url: 'https://thedailyfront.com/write-for-us',
      },
    ],
  },

  editorialTransparency: {
    status: 'good',
    signalStatus: 'VERIFIED_POSITIVE',
    signalState: 'VERIFIED',
    headline: '5 of 6 editorial transparency signals verified',
    aboutPage: { found: true, url: 'https://thedailyfront.com/about-us', title: 'About The Daily Front' },
    contactPage: { found: true, url: 'https://thedailyfront.com/contact', title: 'Contact Our Newsroom' },
    authorProfiles: { found: true, sampleAuthors: ['Elena Rostova', 'Marcus Vance', 'David Chen'], count: 5 },
    editorialPolicy: { found: true, url: 'https://thedailyfront.com/editorial-policy', title: 'Editorial Standards' },
    privacyPolicy: { found: true, url: 'https://thedailyfront.com/privacy-policy', title: 'Privacy Policy' },
    termsOfService: { found: true, url: 'https://thedailyfront.com/terms', title: 'Terms of Service' },
    explanation: 'About, Contact, Privacy, Terms, and named author bylines were identified in sampled pages.',
    evidence: [
      {
        id: 'demo-ed-1',
        type: 'url',
        title: 'About Page: Verified',
        url: 'https://thedailyfront.com/about-us',
      },
      {
        id: 'demo-ed-2',
        type: 'url',
        title: 'Contact Information: Verified',
        url: 'https://thedailyfront.com/contact',
      },
    ],
  },

  contentAuthors: {
    status: 'transparent',
    signalStatus: 'VERIFIED_POSITIVE',
    signalState: 'VERIFIED',
    headline: 'Distinct named authors present on 87% of articles',
    authorNamesFoundCount: 5,
    articlesWithAuthorCount: 13,
    articlesWithDatesCount: 15,
    articlesWithUpdatedDatesCount: 7,
    genericAuthorDetected: false,
    topAuthors: [
      { name: 'Elena Rostova', count: 5 },
      { name: 'Marcus Vance', count: 4 },
      { name: 'David Chen', count: 3 },
      { name: 'Sarah Jenkins', count: 1 },
    ],
    explanation: 'Sampled articles display individual author bylines (5 distinct author names found) and timestamp attribution.',
    evidence: [
      {
        id: 'demo-auth-1',
        type: 'stat',
        title: '13 / 15 articles show named author bylines',
        detail: 'Sample: Elena Rostova, Marcus Vance, David Chen',
      },
    ],
  },

  technicalChecks: {
    status: 'good',
    signalStatus: 'VERIFIED_POSITIVE',
    signalState: 'VERIFIED',
    headline: 'Technical accessibility & discovery files verified',
    isHttps: true,
    httpToHttpsRedirect: true,
    redirectCount: 0,
    redirectChain: [],
    robotsTxtFound: true,
    robotsTxtUrl: 'https://thedailyfront.com/robots.txt',
    robotsAllowsCrawling: true,
    sitemapFound: true,
    sitemapUrl: 'https://thedailyfront.com/sitemap.xml',
    sitemapType: 'index',
    canonicalTagsRatio: 1.0,
    noindexDetectedCount: 0,
    statusCode: 200,
    responseSpeedMs: 280,
    explanation: 'HTTPS verified, robots.txt and sitemap accessible, and canonical tags detected on sampled articles.',
    evidence: [
      {
        id: 'demo-tech-1',
        type: 'stat',
        title: 'HTTPS Security: Verified',
      },
      {
        id: 'demo-tech-2',
        type: 'stat',
        title: 'robots.txt: Found',
        url: 'https://thedailyfront.com/robots.txt',
      },
    ],
  },

  sampledPages: [
    {
      url: 'https://thedailyfront.com/tech/scaling-remote-engineering',
      title: 'How Remote Teams Scale Engineering Velocity',
      publishDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      author: 'Elena Rostova',
      externalLinksCount: 3,
      internalLinksCount: 8,
      hasSponsoredLinks: false,
      wordCount: 1200,
      articleConfidence: 0.95,
      isVerifiedArticle: true,
    },
    {
      url: 'https://thedailyfront.com/travel/top-boutique-hotels-europe',
      title: 'Top Boutique Hotels in Southern Europe for 2026',
      publishDate: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      author: 'Marcus Vance',
      externalLinksCount: 7,
      internalLinksCount: 6,
      hasSponsoredLinks: false,
      wordCount: 1450,
      articleConfidence: 0.92,
      isVerifiedArticle: true,
    },
    {
      url: 'https://thedailyfront.com/tech/best-devops-monitoring-stacks',
      title: 'Best DevOps Monitoring Stacks for High-Throughput APIs',
      publishDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      author: 'David Chen',
      externalLinksCount: 8,
      internalLinksCount: 5,
      hasSponsoredLinks: false,
      wordCount: 1800,
      articleConfidence: 0.94,
      isVerifiedArticle: true,
    },
    {
      url: 'https://thedailyfront.com/finance/sustainable-investing-guide',
      title: 'Navigating Sustainable Investing & Clean Tech Funds',
      publishDate: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      author: 'Elena Rostova',
      externalLinksCount: 4,
      internalLinksCount: 7,
      hasSponsoredLinks: true,
      wordCount: 1100,
      articleConfidence: 0.9,
      isVerifiedArticle: true,
    },
  ],
  totalPagesDiscovered: 48,
  crawlDurationMs: 1420,
  categories: {
    status: 'detected',
    signalStatus: 'VERIFIED_POSITIVE',
    signalState: 'VERIFIED',
    headline: 'Listed Categories',
    count: 4,
    sourcesFound: ['main navigation menus'],
    categories: [
      { name: 'Technology', url: 'https://thedailyfront.com/tech', source: 'navigation' },
      { name: 'Travel', url: 'https://thedailyfront.com/travel', source: 'navigation' },
      { name: 'Finance', url: 'https://thedailyfront.com/finance', source: 'navigation' },
      { name: 'Lifestyle', url: 'https://thedailyfront.com/lifestyle', source: 'navigation' },
    ],
    explanation: 'PublisherCheck identified 4 publicly declared categories in the website\'s accessible first-party structure (main navigation menus). Exact category names are reported as declared by the website.',
    evidence: [
      {
        id: 'demo-cat-1',
        type: 'stat',
        title: 'Publicly Declared Category Structure',
        detail: 'Found 4 category names through main navigation menus at thedailyfront.com.',
      },
    ],
  },
};
